global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_wait: 10s  # Time to wait before sending a notification for the first alert in a group
  group_interval: 1m  # Minimum interval between notifications for the same alert group
  repeat_interval: 3h  # Minimum interval between repeated notifications for the same alert group
  receiver: 'slack-notifications'

receivers:
  - name: 'slack-notifications'
    slack_configs:
      - api_url: 'https://hooks.slack.com/services/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'
        channel: '#general'
        send_resolved: true
        title: '{{ template "slack.default.title" . }}'
        text: '{{ template "slack.default.text" . }}'
