global:
  scrape_interval: 10s
  evaluation_interval: 10s

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

rule_files:
  - "/etc/prometheus/rules.yml"

scrape_configs:
  - job_name: 'web-service'
    docker_sd_configs:
      - host: "unix:///var/run/docker.sock"
    relabel_configs:
      - source_labels: [__meta_docker_container_label_prometheus_job]
        action: keep
        regex: web
      - source_labels: [__address__, __meta_docker_container_port]
        separator: ':'
        regex: (.*):(\d+)
        target_label: __address__
        replacement: $1:$2